#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the equalizeArray function below.
def equalizeArray(arr):
    dict={}
    max=1
    for i in range(n):
        a=arr[i]
        if a in dict:
            dict[a]+=1
            max=dict[a] if dict[a]>max else max
        else:
            dict[a]=1
    res=sum(dict.values())-max
    return res

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    result = equalizeArray(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
